// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PharmacyBenefitManagement.Repo.DataContext;

#nullable disable

namespace PharmacyBenefitManagement.Migrations
{
    [DbContext(typeof(PbmDbContext))]
    [Migration("20260131191727_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PharmacyBenefitManagement.Domain.Entities.Claim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClaimStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DenialCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DenialReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DrugCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DrugName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FiledDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<decimal>("MemberResponsibility")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PlanCodeSnapshot")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Claim_ClaimNumber");

                    b.HasIndex("MemberId", "ServiceDate", "ClaimStatus")
                        .IsDescending(false, true, false)
                        .HasDatabaseName("IX_Claim_MemberId_ServiceDate_Status");

                    b.ToTable("Claims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimNumber = "CLM-2024-001",
                            ClaimStatus = "Paid",
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2025, 12, 17, 19, 17, 26, 583, DateTimeKind.Utc).AddTicks(5439),
                            DrugCode = "00002-7510-01",
                            DrugName = "Lisinopril 10mg",
                            FiledDate = new DateTime(2024, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 1,
                            MemberResponsibility = 15.00m,
                            PaidAmount = 135.00m,
                            PlanCodeSnapshot = "PREMIUM-001",
                            Provider = "City Pharmacy",
                            ServiceDate = new DateTime(2024, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 150.00m
                        },
                        new
                        {
                            Id = 2,
                            ClaimNumber = "CLM-2024-002",
                            ClaimStatus = "Paid",
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 19, 17, 26, 583, DateTimeKind.Utc).AddTicks(5439),
                            DrugCode = "00378-6110-93",
                            DrugName = "Metformin 500mg",
                            FiledDate = new DateTime(2024, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 1,
                            MemberResponsibility = 10.00m,
                            PaidAmount = 75.00m,
                            PlanCodeSnapshot = "PREMIUM-001",
                            Provider = "General Hospital Pharmacy",
                            ServiceDate = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 85.00m
                        },
                        new
                        {
                            Id = 3,
                            ClaimNumber = "CLM-2024-003",
                            ClaimStatus = "Pending",
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 21, 19, 17, 26, 583, DateTimeKind.Utc).AddTicks(5439),
                            DrugCode = "00093-0058-01",
                            DrugName = "Atorvastatin 20mg",
                            FiledDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 1,
                            MemberResponsibility = 0.00m,
                            PaidAmount = 0.00m,
                            PlanCodeSnapshot = "PREMIUM-001",
                            Provider = "Wellness Pharmacy",
                            ServiceDate = new DateTime(2024, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 120.00m
                        },
                        new
                        {
                            Id = 4,
                            ClaimNumber = "CLM-2024-004",
                            ClaimStatus = "Paid",
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2025, 12, 22, 19, 17, 26, 583, DateTimeKind.Utc).AddTicks(5439),
                            DrugCode = "59762-0028-01",
                            DrugName = "Amoxicillin 500mg",
                            FiledDate = new DateTime(2024, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 2,
                            MemberResponsibility = 10.00m,
                            PaidAmount = 35.00m,
                            PlanCodeSnapshot = "BASIC-001",
                            Provider = "Downtown Pharmacy",
                            ServiceDate = new DateTime(2024, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 45.00m
                        },
                        new
                        {
                            Id = 5,
                            ClaimNumber = "CLM-2024-005",
                            ClaimStatus = "Denied",
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 16, 19, 17, 26, 583, DateTimeKind.Utc).AddTicks(5439),
                            DenialCode = "PA-REQ",
                            DenialReason = "Prior authorization required",
                            DrugCode = "00172-5363-70",
                            DrugName = "Synthroid 50mcg",
                            FiledDate = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 2,
                            MemberResponsibility = 0.00m,
                            PaidAmount = 0.00m,
                            PlanCodeSnapshot = "BASIC-001",
                            Provider = "Community Health Pharmacy",
                            ServiceDate = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 95.00m
                        },
                        new
                        {
                            Id = 6,
                            ClaimNumber = "CLM-2024-006",
                            ClaimStatus = "Paid",
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2025, 11, 12, 19, 17, 26, 583, DateTimeKind.Utc).AddTicks(5439),
                            DrugCode = "00781-1506-01",
                            DrugName = "Warfarin 5mg",
                            FiledDate = new DateTime(2024, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 3,
                            MemberResponsibility = 10.00m,
                            PaidAmount = 55.00m,
                            PlanCodeSnapshot = "MEDICARE-D-001",
                            Provider = "Senior Care Pharmacy",
                            ServiceDate = new DateTime(2024, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 65.00m
                        });
                });

            modelBuilder.Entity("PharmacyBenefitManagement.Domain.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MemberId")
                        .IsUnique()
                        .HasDatabaseName("IX_Member_MemberId");

                    b.HasIndex("MemberId", "IsActive")
                        .HasDatabaseName("IX_Member_MemberId_IsActive");

                    b.ToTable("Members", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 1, 31, 19, 17, 26, 583, DateTimeKind.Utc).AddTicks(5439),
                            DateOfBirth = new DateTime(1975, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            IsActive = true,
                            LastName = "Anderson",
                            MemberId = "M001"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 1, 31, 19, 17, 26, 583, DateTimeKind.Utc).AddTicks(5439),
                            DateOfBirth = new DateTime(1982, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sarah",
                            IsActive = true,
                            LastName = "Williams",
                            MemberId = "M002"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 1, 31, 19, 17, 26, 583, DateTimeKind.Utc).AddTicks(5439),
                            DateOfBirth = new DateTime(1945, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Robert",
                            IsActive = true,
                            LastName = "Martinez",
                            MemberId = "M003"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2025, 1, 31, 19, 17, 26, 583, DateTimeKind.Utc).AddTicks(5439),
                            DateOfBirth = new DateTime(1990, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnrollmentDate = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Emily",
                            IsActive = false,
                            LastName = "Johnson",
                            MemberId = "M004"
                        });
                });

            modelBuilder.Entity("PharmacyBenefitManagement.Domain.Entities.MemberPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroupNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<string>("RelationshipToSubscriber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("MemberId", "EffectiveDate", "TerminationDate")
                        .HasDatabaseName("IX_MemberPlan_MemberId_Dates");

                    b.ToTable("MemberPlans", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 1, 31, 19, 17, 26, 583, DateTimeKind.Utc).AddTicks(5439),
                            EffectiveDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupNumber = "GRP-12345",
                            MemberId = 1,
                            PlanId = 1,
                            RelationshipToSubscriber = "Self",
                            TerminationDate = new DateTime(2024, 12, 31, 23, 59, 59, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 1, 31, 19, 17, 26, 583, DateTimeKind.Utc).AddTicks(5439),
                            EffectiveDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupNumber = "GRP-67890",
                            MemberId = 2,
                            PlanId = 2,
                            RelationshipToSubscriber = "Self"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 1, 31, 19, 17, 26, 583, DateTimeKind.Utc).AddTicks(5439),
                            EffectiveDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MemberId = 3,
                            PlanId = 3,
                            RelationshipToSubscriber = "Self"
                        });
                });

            modelBuilder.Entity("PharmacyBenefitManagement.Domain.Entities.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Deductible")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OutOfPocketMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PlanCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlanCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Plan_PlanCode");

                    b.HasIndex("PlanCode", "IsActive")
                        .HasDatabaseName("IX_Plan_PlanCode_IsActive");

                    b.ToTable("Plans", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 1, 31, 19, 17, 26, 583, DateTimeKind.Utc).AddTicks(5439),
                            Deductible = 500m,
                            Description = "Comprehensive coverage with nationwide network",
                            EffectiveDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            OutOfPocketMax = 5000m,
                            PlanCode = "PREMIUM-001",
                            PlanName = "Premium Health Plan",
                            PlanType = "PPO"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 1, 31, 19, 17, 26, 583, DateTimeKind.Utc).AddTicks(5439),
                            Deductible = 1000m,
                            Description = "Essential coverage with regional network",
                            EffectiveDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            OutOfPocketMax = 7000m,
                            PlanCode = "BASIC-001",
                            PlanName = "Basic Health Plan",
                            PlanType = "HMO"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "seed",
                            CreatedDate = new DateTime(2026, 1, 31, 19, 17, 26, 583, DateTimeKind.Utc).AddTicks(5439),
                            Deductible = 250m,
                            Description = "Prescription drug coverage for Medicare beneficiaries",
                            EffectiveDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            OutOfPocketMax = 3000m,
                            PlanCode = "MEDICARE-D-001",
                            PlanName = "Medicare Part D Enhanced",
                            PlanType = "Medicare Part D"
                        });
                });

            modelBuilder.Entity("PharmacyBenefitManagement.Domain.Entities.Claim", b =>
                {
                    b.HasOne("PharmacyBenefitManagement.Domain.Entities.Member", "Member")
                        .WithMany("Claims")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("PharmacyBenefitManagement.Domain.Entities.MemberPlan", b =>
                {
                    b.HasOne("PharmacyBenefitManagement.Domain.Entities.Member", "Member")
                        .WithMany("MemberPlans")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PharmacyBenefitManagement.Domain.Entities.Plan", "Plan")
                        .WithMany("MemberPlans")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("PharmacyBenefitManagement.Domain.Entities.Member", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("MemberPlans");
                });

            modelBuilder.Entity("PharmacyBenefitManagement.Domain.Entities.Plan", b =>
                {
                    b.Navigation("MemberPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
